import { exp } from "react-native-reanimated"

export const LABEL_HEADER:string = "Test app"
export const LABEL_VIEW_MORE:string = "View More"
export const LABEL_IMAGE_NOT_FOUND:string = "Image not found"
export const LABEL_NO_RECORD_FOUND:string = "No record found"
export const NO_INTENRT_CONNECTION:string = "No Internet Connection"
export const CHECK_YOUR_INTERNET:string = "Please check your internet connection and try again."
export const OK:string = "OK"
export const NEW_ARRIVALS:string = "New Arrivals"
export const BEST_SELLING_PRODUCTS:string = "Best Selling Products"
export const FAVOURITE_LABEL:string = "FAVOURITE"
export const CART_LABEL:string = "CART"
export const LoaderColor:string = "#0000ff"