//Screen navigator
export const DashboardNavigator = "Dashboard"
export const ProductNavigator = "Product"
export const ProductDetailNavigator = "ProductDetail"
export const FullScreenImageViewerNavigator = "FullScreenImageViewer"
export const FavouriteNavigator = "Favourite"
export const RegisterNavigator = "Register"
export const LoginNavigator = "Login"
export const BillingInfoNavigator = "BillingInfo"
export const SubCategoryNavigator = "SubCategory"
export const SubCategoryMoreNavigator = "SubCategoryMore"
export const orderHistoryNavigator = "OrderHistory"
export const orderDetailHistoryNavigator = "orderDetail"

//Bottom bar navigator
export const HomeTabNavigator = "Home"
export const categoryTabNavigator = "category"
export const FavouriteTabNavigator = "Favourite"
export const SettingTabNavigator = "Setting"
export const CartNavigator = "Cart"